//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriBotV4.Dialogs.AskAri.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SearchAri {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearchAri() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AriBotV4.Dialogs.AskAri.Resources.SearchAri", typeof(SearchAri).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask Ari.
        /// </summary>
        internal static string AskAri {
            get {
                return ResourceManager.GetString("AskAri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure. Tell me how can I help.
        /// </summary>
        internal static string AskAriHelp {
            get {
                return ResourceManager.GetString("AskAriHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you looking for? You can type in a question like:
        ///- What is AI?
        ///- Why do we celebrate Christmas?.
        /// </summary>
        internal static string AskAriSample {
            get {
                return ResourceManager.GetString("AskAriSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which state or city you are looking for?.
        /// </summary>
        internal static string AskCityorState {
            get {
                return ResourceManager.GetString("AskCityorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please elaborate little more.
        /// </summary>
        internal static string AskMoreInfo {
            get {
                return ResourceManager.GetString("AskMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me more:.
        /// </summary>
        internal static string ChooseAriOptions {
            get {
                return ResourceManager.GetString("ChooseAriOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell me more:.
        /// </summary>
        internal static string ChooseOptions {
            get {
                return ResourceManager.GetString("ChooseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaborate more.
        /// </summary>
        internal static string ConfirmAskForMoreInfo {
            get {
                return ResourceManager.GetString("ConfirmAskForMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you happy with the result?.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string ConfirmFeedback {
            get {
                return ResourceManager.GetString("ConfirmFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ConfirmNo {
            get {
                return ResourceManager.GetString("ConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ConfirmYes {
            get {
                return ResourceManager.GetString("ConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Date : .
        /// </summary>
        internal static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Time : .
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly provide me with more details.
        /// </summary>
        internal static string ElaborateMoreDetails {
            get {
                return ResourceManager.GetString("ElaborateMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye.
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like you are not happy with the results. I have taken your input and will try to do better in the future..
        /// </summary>
        internal static string Improve {
            get {
                return ResourceManager.GetString("Improve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is what I found for you on the internet. Is it what you are looking for?.
        /// </summary>
        internal static string InternetConfirmation {
            get {
                return ResourceManager.GetString("InternetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not find what you are looking for..
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I could not find what you are looking for so I searched the internet for you..
        /// </summary>
        internal static string QnAMakerAnswerNotFound {
            get {
                return ResourceManager.GetString("QnAMakerAnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did not understand what you meant, can you please try again?.
        /// </summary>
        internal static string RepromptConfirmation {
            get {
                return ResourceManager.GetString("RepromptConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search internet.
        /// </summary>
        internal static string Searchinternet {
            get {
                return ResourceManager.GetString("Searchinternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. I hope your experience was awesome. Can&apos;t wait to see you again soon!.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was I useful?.
        /// </summary>
        internal static string Useful {
            get {
                return ResourceManager.GetString("Useful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
    }
}
