//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriBotV4.Dialogs.Deals.Food.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FoodDeals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FoodDeals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AriBotV4.Dialogs.Deals.Food.Resources.FoodDeals", typeof(FoodDeals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve?.
        /// </summary>
        internal static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which cuisine do you want today?.
        /// </summary>
        internal static string AskFoodPrefrence {
            get {
                return ResourceManager.GetString("AskFoodPrefrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many people are dining? Any location in mind?.
        /// </summary>
        internal static string AskPeople {
            get {
                return ResourceManager.GetString("AskPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastly, around what time do you want to book?.
        /// </summary>
        internal static string AskTime {
            get {
                return ResourceManager.GetString("AskTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The booking is made and here is the fastest route to get there...
        /// </summary>
        internal static string BookingConfirmation {
            get {
                return ResourceManager.GetString("BookingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For {0} cuisine, we have ... Do you want me to make a booking?.
        /// </summary>
        internal static string ConfirmBooking {
            get {
                return ResourceManager.GetString("ConfirmBooking", resourceCulture);
            }
        }
    }
}
