//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriBotV4.Dialogs.TaskSpur.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskSpur {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskSpur() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AriBotV4.Dialogs.TaskSpur.Resources.TaskSpur", typeof(TaskSpur).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address.
        /// </summary>
        internal static string AskEmailID {
            get {
                return ResourceManager.GetString("AskEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it. What is the category?.
        /// </summary>
        internal static string AskGoalCategory {
            get {
                return ResourceManager.GetString("AskGoalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure. What is the Goal name?.
        /// </summary>
        internal static string AskGoalName {
            get {
                return ResourceManager.GetString("AskGoalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For which goal is this task for?.
        /// </summary>
        internal static string AskGoalType {
            get {
                return ResourceManager.GetString("AskGoalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string AskPassword {
            get {
                return ResourceManager.GetString("AskPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe the task or tell me what you need to do in the task?.
        /// </summary>
        internal static string AskTaskDescription {
            get {
                return ResourceManager.GetString("AskTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to call the task?.
        /// </summary>
        internal static string AskTaskName {
            get {
                return ResourceManager.GetString("AskTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the priority of this task for you?.
        /// </summary>
        internal static string AskTaskPriority {
            get {
                return ResourceManager.GetString("AskTaskPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of task is it?.
        /// </summary>
        internal static string AskTypeOfTask {
            get {
                return ResourceManager.GetString("AskTypeOfTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still cannot find the goal?.
        /// </summary>
        internal static string CannotFindGoal {
            get {
                return ResourceManager.GetString("CannotFindGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still cannot find the task?.
        /// </summary>
        internal static string CannotFindTask {
            get {
                return ResourceManager.GetString("CannotFindTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! {0} AM or {1} PM.
        /// </summary>
        internal static string ConfirmAMPM {
            get {
                return ResourceManager.GetString("ConfirmAMPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any more questions for me?.
        /// </summary>
        internal static string ConfirmCommon {
            get {
                return ResourceManager.GetString("ConfirmCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to create another goal?.
        /// </summary>
        internal static string ConfirmCreateGoal {
            get {
                return ResourceManager.GetString("ConfirmCreateGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to create another task?.
        /// </summary>
        internal static string ConfirmCreateTask {
            get {
                return ResourceManager.GetString("ConfirmCreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this task?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there anything else you’re curious about?.
        /// </summary>
        internal static string ConfirmGeneral {
            get {
                return ResourceManager.GetString("ConfirmGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any more questions about your schedule?.
        /// </summary>
        internal static string ConfirmGetTasks {
            get {
                return ResourceManager.GetString("ConfirmGetTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this goal?.
        /// </summary>
        internal static string ConfirmGoalDelete {
            get {
                return ResourceManager.GetString("ConfirmGoalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any more image queries for me?.
        /// </summary>
        internal static string ConfirmImages {
            get {
                return ResourceManager.GetString("ConfirmImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any more news-related questions for me?.
        /// </summary>
        internal static string ConfirmNews {
            get {
                return ResourceManager.GetString("ConfirmNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to have the same reminder? {0} before the task.
        /// </summary>
        internal static string ConfirmRemind {
            get {
                return ResourceManager.GetString("ConfirmRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would that be in minutes, hours, or days?.
        /// </summary>
        internal static string ConfirmReminder {
            get {
                return ResourceManager.GetString("ConfirmReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a task?.
        /// </summary>
        internal static string ConfirmTask {
            get {
                return ResourceManager.GetString("ConfirmTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you happy with this task name?.
        /// </summary>
        internal static string ConfirmTaskName {
            get {
                return ResourceManager.GetString("ConfirmTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Goal.
        /// </summary>
        internal static string CreateGoals {
            get {
                return ResourceManager.GetString("CreateGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Task.
        /// </summary>
        internal static string CreateTasks {
            get {
                return ResourceManager.GetString("CreateTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay. Can you give me the name of the goal you want to delete?.
        /// </summary>
        internal static string DeleteGoalName {
            get {
                return ResourceManager.GetString("DeleteGoalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay. Can you give me the name of the task you want to delete?.
        /// </summary>
        internal static string DeleteTaskName {
            get {
                return ResourceManager.GetString("DeleteTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which category you want to change to?.
        /// </summary>
        internal static string EditGoalCategory {
            get {
                return ResourceManager.GetString("EditGoalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right away! What&apos;s the name of this goal.
        /// </summary>
        internal static string EditGoalName {
            get {
                return ResourceManager.GetString("EditGoalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay. Please enter the new name you prefer.
        /// </summary>
        internal static string EditGoalNewname {
            get {
                return ResourceManager.GetString("EditGoalNewname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! How should we proceed?
        ///You can say:
        ///Create a new task
        ///Get my task
        ///Edit a task
        ///Delete a task.
        /// </summary>
        internal static string EditTaskInput {
            get {
                return ResourceManager.GetString("EditTaskInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay. Please enter the new task name you prefer.
        /// </summary>
        internal static string EditTaskName {
            get {
                return ResourceManager.GetString("EditTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! What kind of change would you like to make?.
        /// </summary>
        internal static string EditTaskOption {
            get {
                return ResourceManager.GetString("EditTaskOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the new priority level.
        /// </summary>
        internal static string EditTaskPriority {
            get {
                return ResourceManager.GetString("EditTaskPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can I help you with?
        ///.
        /// </summary>
        internal static string GetTaskInput {
            get {
                return ResourceManager.GetString("GetTaskInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string GetTasks {
            get {
                return ResourceManager.GetString("GetTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string GoalCategory {
            get {
                return ResourceManager.GetString("GoalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You forgot to give your &lt;b&gt;Goal&lt;/b&gt; a name. 
        ///Please type a name that&apos;s easy to remember..
        /// </summary>
        internal static string GoalEmpty {
            get {
                return ResourceManager.GetString("GoalEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System goal - not deletable.
        /// </summary>
        internal static string GoalNotDeletable {
            get {
                return ResourceManager.GetString("GoalNotDeletable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System goal - not editable.
        /// </summary>
        internal static string GoalNotEditable {
            get {
                return ResourceManager.GetString("GoalNotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your goal has been created now.
        /// </summary>
        internal static string GoalSuccessfullyCreated {
            get {
                return ResourceManager.GetString("GoalSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal not found, try again.
        /// </summary>
        internal static string NoGoalFound {
            get {
                return ResourceManager.GetString("NoGoalFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you don&apos;t have any goals under that Status.
        /// </summary>
        internal static string NoGoals {
            get {
                return ResourceManager.GetString("NoGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task not found, try again.
        /// </summary>
        internal static string NoTaskFound {
            get {
                return ResourceManager.GetString("NoTaskFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The closest setting that I have for the reminder is {0}. Are you happy with this?.
        /// </summary>
        internal static string ReminderClosestMessage {
            get {
                return ResourceManager.GetString("ReminderClosestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string ReminderHappyMessage {
            get {
                return ResourceManager.GetString("ReminderHappyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        internal static string Reschedule {
            get {
                return ResourceManager.GetString("Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problem. Just enter the name of the task..
        /// </summary>
        internal static string SearchTaskName {
            get {
                return ResourceManager.GetString("SearchTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like you are trying to set up a task. Let&apos;s start with the name!.
        /// </summary>
        internal static string SetupTask {
            get {
                return ResourceManager.GetString("SetupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be signed in to be able to use TaskSpur. I have opened another window for you to sign in..
        /// </summary>
        internal static string SignInMessage {
            get {
                return ResourceManager.GetString("SignInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need any guidance or help?.
        /// </summary>
        internal static string SignInOption {
            get {
                return ResourceManager.GetString("SignInOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are successfully logged in!.
        /// </summary>
        internal static string SuccessfulLogin {
            get {
                return ResourceManager.GetString("SuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in after registering and reseting password.
        /// </summary>
        internal static string SuccessfulRegistration {
            get {
                return ResourceManager.GetString("SuccessfulRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve chosen {0}. Is this correct?.
        /// </summary>
        internal static string TaskConfirmDate {
            get {
                return ResourceManager.GetString("TaskConfirmDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! Do you know when you want to do this?.
        /// </summary>
        internal static string TaskDateAndTime {
            get {
                return ResourceManager.GetString("TaskDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! You forgot to give your &lt;b&gt;Task&lt;/b&gt; a name. 
        ///Please type a name that&apos;s easy to remember..
        /// </summary>
        internal static string TaskEmpty {
            get {
                return ResourceManager.GetString("TaskEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When does the task need to end?.
        /// </summary>
        internal static string TaskEndDate {
            get {
                return ResourceManager.GetString("TaskEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time does the task need to end?.
        /// </summary>
        internal static string TaskEndTime {
            get {
                return ResourceManager.GetString("TaskEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date does not seem valid to me. Can you try a different date, for example today, next week or 23 Aug?.
        /// </summary>
        internal static string TaskInvalidDate {
            get {
                return ResourceManager.GetString("TaskInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to remind you of this task?.
        /// </summary>
        internal static string TaskRemindMe {
            get {
                return ResourceManager.GetString("TaskRemindMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long before the task would you like to be reminded? You can set task reminders such as 15 minutes, 2 hours, or 3 days before..
        /// </summary>
        internal static string TaskRemindTime {
            get {
                return ResourceManager.GetString("TaskRemindTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string TaskSpurChoose {
            get {
                return ResourceManager.GetString("TaskSpurChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is TaskSpur?.
        /// </summary>
        internal static string TaskSpurInfo {
            get {
                return ResourceManager.GetString("TaskSpurInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When does the task need to start?.
        /// </summary>
        internal static string TaskStartDate {
            get {
                return ResourceManager.GetString("TaskStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure! Do you know what time?
        ///.
        /// </summary>
        internal static string TaskStartTime {
            get {
                return ResourceManager.GetString("TaskStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great! What time?.
        /// </summary>
        internal static string TaskTime {
            get {
                return ResourceManager.GetString("TaskTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time does not seem valid to me. Can you try a different time, for example 3 pm or 10 am?.
        /// </summary>
        internal static string TaskValidTime {
            get {
                return ResourceManager.GetString("TaskValidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
