//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AriBotV4.Dialogs.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AriBotV4.Dialogs.Common.Resources.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ari Bot].
        /// </summary>
        internal static string AriBot {
            get {
                return ResourceManager.GetString("AriBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For which city you like to get weather report?.
        /// </summary>
        internal static string AskCity {
            get {
                return ResourceManager.GetString("AskCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certainly, can I use your stored Card?.
        /// </summary>
        internal static string AskedStoreCard {
            get {
                return ResourceManager.GetString("AskedStoreCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it {0}! And can I have your email address please?.
        /// </summary>
        internal static string AskEmail {
            get {
                return ResourceManager.GetString("AskEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}. How can I help you today?.
        /// </summary>
        internal static string AskHelp {
            get {
                return ResourceManager.GetString("AskHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave your name.
        /// </summary>
        internal static string AskName {
            get {
                return ResourceManager.GetString("AskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am excited about your awesome idea. Tell me more.
        /// </summary>
        internal static string AwesomeIdea {
            get {
                return ResourceManager.GetString("AwesomeIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, please choose an option below.
        /// </summary>
        internal static string ChooseDeals {
            get {
                return ResourceManager.GetString("ChooseDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the dialog else tell me anything to request for my help again..
        /// </summary>
        internal static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ConfirmNo {
            get {
                return ResourceManager.GetString("ConfirmNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ConfirmYes {
            get {
                return ResourceManager.GetString("ConfirmYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its been long, Waiting for your response!.
        /// </summary>
        internal static string FirstAttempBusy {
            get {
                return ResourceManager.GetString("FirstAttempBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you and goodbye.
        /// </summary>
        internal static string Goodbye {
            get {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome! Happy to help you.
        /// </summary>
        internal static string HappyToHelp {
            get {
                return ResourceManager.GetString("HappyToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was I helpful?.
        /// </summary>
        internal static string Helpful {
            get {
                return ResourceManager.GetString("Helpful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your feedback. Could you please tell me a bit on why you didn&apos;t like it?.
        /// </summary>
        internal static string Improve {
            get {
                return ResourceManager.GetString("Improve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is there anything else I can do for you?.
        /// </summary>
        internal static string NeedAnything {
            get {
                return ResourceManager.GetString("NeedAnything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry but I could not find what you are looking for. Please try again with a different request..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to proceed?.
        /// </summary>
        internal static string proceed {
            get {
                return ResourceManager.GetString("proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search again.
        /// </summary>
        internal static string SearchAgain {
            get {
                return ResourceManager.GetString("SearchAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seems to be busy. Goodbye!.
        /// </summary>
        internal static string SecondAttempGoodBuy {
            get {
                return ResourceManager.GetString("SecondAttempGoodBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, I didn&apos;t understand your message. Can you type it again?.
        /// </summary>
        internal static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I could not find a match for your search..
        /// </summary>
        internal static string SorryNotFound {
            get {
                return ResourceManager.GetString("SorryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am still being trained on this feature right now but I will let you know once it is ready.
        /// </summary>
        internal static string StillInProgress {
            get {
                return ResourceManager.GetString("StillInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your feedback. I will consider your comment to further improve my performance..
        /// </summary>
        internal static string ThankyouForFeedback {
            get {
                return ResourceManager.GetString("ThankyouForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for subscribing to our Newsletters. Amazing articles and other cool stuff are coming. So stay tuned!.
        /// </summary>
        internal static string ThankyouForNewsLetter {
            get {
                return ResourceManager.GetString("ThankyouForNewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for that cool idea. We will look into it and get back to you shortly..
        /// </summary>
        internal static string ThankyouForSharing {
            get {
                return ResourceManager.GetString("ThankyouForSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        internal static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry but the free internet search is currently disabled until the first of the following month..
        /// </summary>
        internal static string WebSearchExpired {
            get {
                return ResourceManager.GetString("WebSearchExpired", resourceCulture);
            }
        }
    }
}
